sudo: true

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo pip install configparser

install:
  - cd ~/build/HMRecord/website
  - sudo ./install.sh
  - echo "[admin]" > config.ini
  - echo "password = d" >> config.ini

script:
  - cd ~/build/HMRecord/website
  - sudo ./runTests.sh

notifications:
  slack: frclions:ijRxNQTNjtcARegMTPC3sLbf
