sudo: true

language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq

install:
  - cd ~/build/HMRecord/website
  - ./install

script:
  - cd ~/build/HMRecord/website
  - ./runTests
